config/routes.rb
Rails.application.routes.draw do
  
  get 'search/index'

  get 'search/show'

  get 'site/index', as: 'about'

  devise_for :users
  
  resources :locations
  resources :users

  root to: 'search#index'

  

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :user, required: true
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :locations
  has_many :profiles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 include Pundit
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
	def user_not_authorized
		flash[:alert] = "You are not authorized to perform this action."
		redirect_to(request.referrer || root_path)
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /locations
  # GET /locations.json
  def index
    @locations = current_user.locations
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    authorize @location
  end

  # GET /locations/new
  def new
    @location = current_user.locations.build
  end

  # GET /locations/1/edit
  def edit
    authorize @location
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = current_user.locations.build(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    authorize @location
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    authorize @location
    @location.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:movie, :location, :image)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  	if params[:q]
  	resp = Typhoeus.get("https://data.sfgov.org/resource/yitu-d5am.json", :params => {:title => params[:q]})
  	json_resp = JSON.parse(resp.body)
    
  	@search = json_resp
    @movie = []
    @location = []
  else
  	@search = []
    @movie = []
    @location = []
  end
  end

  def show
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def index
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
  def index
    @location = current_user.locations
  end

  def show
    if current_user
    @user = current_user
    @info = current_user.profiles
    else
      redirect_to new_user_session_path
    end  
  end

  def new
  end

  def edit
  end

  def create
  end

  def destroy
  end

  # private

  #   def content_params
  #     params.require(:profile).permit(:name, :origin, :location_pic, :comment, :user_id)
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>	
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	 <title>SceneInTheCity</title>
	 <link href='http://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
	 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	 <%= csrf_meta_tags %>
	<link rel="stylesheet">
            <!-- Latest compiled and minified CSS image_tag --> 
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	</head>
	<body style="background:url(<%= asset_path('cover.jpg')%>) no-repeat center center fixed;background-size: cover;-webkit-background-size: cover;-moz-background-size: cover;font-family:Ubuntu;font-size:16px;padding-top:150px;">

	<nav class="navbar navbar-default navbar-fixed-top myNav">
				<div class="container-fluid">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
				   
					<a href="/"><img src='<%= asset_path('logo_1.png') %>' class="img-responsive" style="height:60px;"></a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav navbar-right">
							<li><%= link_to "About Us", '/site/index' %></li>
							<% if user_signed_in? %>
				  				<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
							<% else %>
				  				<li><%= link_to "Sign in", new_user_session_path %></li>
							<% end %>
							<li><%= link_to "Search", search_index_path %></li>
							<li><%= link_to "Profile", '/users' %></li>


						</ul>
					</div><!-- /.navbar-collapse -->
				</div><!-- /.container-fluid -->
			</nav>
<div class="container">
  <%= yield %>
</div>



</body>
					<p class="notice"><%= notice %></p>
					<p class="alert"><%= alert %></p>
</html>     

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %>
  </div>
  <div class="field imgs">
    
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :movie %><br>
    <%= f.text_field :movie %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit "Save Favorite" %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1 class="about_name">Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', users_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>
<link href='http://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
<h1 class="background">Favorite Locations</h1>


  <h3 class= "index_row clearfix">
    <li>
      <th class="title">Location:</th>
      <th colspan="3"></th>
    </tr>
  </h3>

  
    <% @locations.each do |location| %>
      
        <li class="sub_title"><%= location.location %></li> <br>
        <li><%= image_tag location.image.url(:medium) %></li><br>
        
        <%= link_to 'Show', location if policy(location).show? %><br>
        <%= link_to 'Edit', edit_location_path(location) if policy(location).edit? %><br>
        <%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } if policy(location).destroy? %>
        </li>
      
    <% end %>
  




<div class="sub_title"><%= link_to 'Create New Favorite', new_location_path %></div>

app/views/locations/new.html.erb
<h1 class="about_name">New Favorite Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<link href='http://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>


<p class="title">
  <strong>Location:</strong>
  <%= @location.location %>
</p>

<%= image_tag @location.image.url(:large) %> </br>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', users_path %>

app/views/search/index.html.erb
<!DOCTYPE html>
<html onload = "map.js">
<head>
  <style type="text/css">
      #map-canvas { height: 500px }; 
    </style>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBdg8HS-G4Xg_eo7LfmT8Z7mO6EFarQxDk"></script>
    <link href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet"></link>
    <link rel="stylesheet">

    
    
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js" ></script>

</head>

<body>


<h1 class="about_name">Discover San Francisco's movie and tv-series locations:</h1>  

  <%= form_tag("/search/index", method: "get") do %>
    <%= text_field_tag :q , nil, :placeholder => 'Enter a movie that was filmed in the city' %>
    <%= submit_tag ("Search")  %>
  <% end %>

  <div id="map-canvas"></div> 
  <br>
  <br>

  <div class="results_list">  

  <% @search.each_with_index do |x,index| %>
    <% @movie.push(x["title"]) %>
    <% @location.push(x["locations"]) %>

  
    <% if index == 0 then%>
      <h2 class="background" id = "t"><%= x["title"] %></h2>
    <%end%>
    <% if @movie[index] != @movie[index-1] then%>
      <h1 class="background" id = "t"><%= x["title"] %></h1>
    <%end%>
    <div class = "loKos">
      <li class="background"><%= x["locations"] %></li>
    </div>        
    <% end %>
  
  </div>


   <%= javascript_include_tag 'maps'%>
  <br>
  <button> <a href="/locations/new">Add a Location to Favorites</a> </button>
  <br>
  <br>
</body>
</html>

app/views/site/index.html.erb
			<h2 class='about_name'>About us:</h2>
			<h4 class='about_name'>Click on the image to see contributions</h4>
					<script>
						$(document).ready(function(){
    					$('[data-toggle="popover"]').popover(); 
						});
					</script>
				
				<img src='<%= asset_path('alex.png') %>' data-toggle= "popover" data-trigger= 'click' data-placement="right" data-content="Project Manager: Organized and outlined project in advance which led to completion of MVP by COB Day 1.GIT Lead: Updated Github Repository to safely move updates from individual branches to the final project branch. Google Maps API v3 Engineer: Used google maps documentation to render a google map and place markers on the map using javascript in a rails environment. Ex-Banker, Math Major, 5.0 Tennis Player." class='about_pic'/>
				<h2 class='about_name'>Alex Trzeciak</h2>
				<p class='positions'>Project Manager, API Integration</p>

				<img src= '<%= asset_path('heidi.png') %>' class='about_pic' data-toggle="popover" data-placement="left" data-content="Being a movie nerd and loving her new home town, Heidi came up with the original idea of Scene in the City. The former journalist came up with all the necessary APIs and researched the SF Open Data and Google Maps API documentation. Heidi helped Alex with API integration and gave the app it’s final stylings."/>
				<h2 class='about_name'>Heidi Kähkönen</h2>
				<p class='positions'>Original idea, API Integration</p>

				<img src= '<%= asset_path('testmark.png') %>' class='about_pic' data-toggle="popover" data-placement="right" data-content="Mark created the logo and website design in Styling CSS using Bootstrap for the front-end. In the back-end development, Mark was responsible for Authorization of users logged in and password security to maintain privacy. He utilized Pundit gem for Ruby on Rails 4 and set up models for storing images."/>
				<h2 class='about_name'>Mark Blum</h2>
				<p class='positions'>Authorization, Styling</p>
			
				<img src='<%= asset_path('david.png') %>' class='about_pic' data-toggle="popover" data-placement="right" data-content="Foreign Language Instructor turned Web Developer. After a lengthy career as an English teacher in Japan I decided to pursue my long held passion for coding." />
				<h2 class='about_name'>David Spencer</h2>
				<p class='positions'>Back-end, Authentication</p>
			

app/views/users/index.html.erb
<h1 class="about_name">Welcome Home</h1>

<div class="about_name" class="sub_title"><%= link_to 'Create New Favorite', new_location_path %></div>


    <% @location.each do |location| %>
      
        <li class="fav_img"><%= image_tag location.image.url(:large) %></li><br>
        
        <div class="edit_options">
	        <li class="about_name"><%= link_to 'Show', location if policy(location).show? %></li><br>
	        <li class="about_name"><%= link_to 'Edit', edit_location_path(location) if policy(location).edit? %></li><br>
	        <li class="about_name"><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } if policy(location).destroy? %></li>
     
  		</div>
    <% end %>
  

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= @user.email %><br>

<%= @info.name %>